export default {
  pathPrefix: "/",
  siteTitle: "Jesús Mendoza | Software Engineer",
  siteTitleAlt: "Jesús Mendoza | Software Engineer",
  siteTitleManifest: "Jesús Mendoza | Software Engineer",
  siteUrl: "https://www.mendozajesus.com",
  siteLanguage: "es",
  siteHeadline: "Jesús Mendoza | Software Engineer, Writer, and Builder",
  siteBanner: "",
  favicon: "../assets/favicon.ico",
  siteDescription:
    "Jesús Mendoza is a software engineer writing and building clear, dependable systems for the web and AI.",
  author: "Jesús Mendoza",
  siteLogo: "",
  keywords: [
    "Software Engineer",
    "JavaScript Developer",
    "React Developer",
    "AI Engineering",
    "Technical Writing",
  ],
  userTwitter: "@JesusReveron",
  ogSiteName: "Jesús Mendoza",
  ogLanguage: "es_ES",
  googleAnalyticsID: "UA-58977019-2",
};
